In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
# Check for the null values 
dataset.isna().apply(pd.value_counts)

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
False      10000       10000    10000        10000      10000   10000  10000   

       Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
False   10000    10000          10000      10000           10000   

       EstimatedSalary  Exited  
False            10000   10000

In [5]:
#check the correlation of the data
dataset.corr()

RowNumber  CustomerId  CreditScore       Age    Tenure  \
RowNumber         1.000000    0.004202     0.005840  0.000783 -0.006495   
CustomerId        0.004202    1.000000     0.005308  0.009497 -0.014883   
CreditScore       0.005840    0.005308     1.000000 -0.003965  0.000842   
Age               0.000783    0.009497    -0.003965  1.000000 -0.009997   
Tenure           -0.006495   -0.014883     0.000842 -0.009997  1.000000   
Balance          -0.009067   -0.012419     0.006268  0.028308 -0.012254   
NumOfProducts     0.007246    0.016972     0.012238 -0.030680  0.013444   
HasCrCard         0.000599   -0.014025    -0.005458 -0.011721  0.022583   
IsActiveMember    0.012044    0.001665     0.025651  0.085472 -0.028362   
EstimatedSalary  -0.005988    0.015271    -0.001384 -0.007201  0.007784   
Exited           -0.016571   -0.006248    -0.027094  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber       -0.009067       0.007246   0.000599        0.012044   
CustomerId      -0.012419       0.016972  -0.014025        0.001665   
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
RowNumber              -0.005988 -0.016571  
CustomerId              0.015271 -0.006248  
CreditScore            -0.001384 -0.027094  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

In [6]:
df_encoded=pd.get_dummies(dataset, columns=['Geography','Gender'])
df_encoded.head()

RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0          1    15634602  Hargrave          619   42       2       0.00   
1          2    15647311      Hill          608   41       1   83807.86   
2          3    15619304      Onio          502   42       8  159660.80   
3          4    15701354      Boni          699   39       1       0.00   
4          5    15737888  Mitchell          850   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              1          1               1        101348.88       1   
1              1          0               1        112542.58       0   
2              3          1               0        113931.57       1   
3              2          0               0         93826.63       0   
4              1          1               1         79084.10       0   

   Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                 1                  0                0              1   
1                 0                  0                1              1   
2                 1                  0                0              1   
3                 1                  0                0              1   
4                 0                  0                1              1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

In [7]:
X=df_encoded[['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Geography_France','Geography_Germany','Geography_Spain','Gender_Female','Gender_Male']].values

In [8]:
y=df_encoded[['Exited']]

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 1- Class SGD

In [11]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6176 - accuracy: 0.7960
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5440 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5201 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5115 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5082 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5068 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5063 - accuracy: 0.7960
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5059 - accuracy: 0.7960
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5059 - accura

In [12]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1500,   95],
       [ 179,  226]], dtype=int64)

In [13]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.3 %


# 2- Class Adagrad

In [14]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'Adagrad', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6878 - accuracy: 0.7945
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6829 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6797 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6771 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6748 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6728 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6709 - accuracy: 0.7960
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6691 - accuracy: 0.7960
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6674 - accuracy: 0.7960
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6658 - accura

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 961us/step


array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [16]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  79.75 %


# 3- Class Adadelta

In [17]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'Adadelta', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6931 - accuracy: 0.7086
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6930 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6928 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6927 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6925 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6923 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6921 - accuracy: 0.7960
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6919 - accuracy: 0.7960
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6917 - accuracy: 0.7960
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6915 - accura

In [18]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 932us/step


array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [19]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  79.75 %


# 4- Class RMSprop

In [20]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'RMSprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.5818 - accuracy: 0.7950
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4486 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4356 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4309 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4291 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4275 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4263 - accuracy: 0.7960
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4251 - accuracy: 0.7994
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4235 - accuracy: 0.8154
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4212 - accura

In [21]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 926us/step


array([[1534,   61],
       [ 261,  144]], dtype=int64)

In [22]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.89999999999999 %


# 5- Class Adam

In [23]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.5642 - accuracy: 0.7959
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4380 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4309 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4282 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4256 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4229 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.8062
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8207
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4180 - accuracy: 0.8235
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4172 - accura

In [24]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 725us/step


array([[1538,   57],
       [ 254,  151]], dtype=int64)

In [25]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  84.45 %


# 6- Class Adamax

In [26]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6516 - accuracy: 0.7930
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5278 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4603 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4484 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4429 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4389 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4358 - accuracy: 0.7960
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4334 - accuracy: 0.7960
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.7960
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4304 - accura

In [27]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 953us/step


array([[1542,   53],
       [ 265,  140]], dtype=int64)

In [28]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  84.1 %


# 7- Class Nadam

In [29]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'Nadam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 2ms/step - loss: 0.5681 - accuracy: 0.7939
Epoch 2/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4382 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4306 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4268 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4241 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4214 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4192 - accuracy: 0.8094
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accuracy: 0.8206
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4166 - accuracy: 0.8250
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4152 - accura

In [30]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 901us/step


array([[1536,   59],
       [ 262,  143]], dtype=int64)

In [31]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.95 %


# 8- Class AMSgrad: is a recent proposed improvement to Adam

In [32]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
optimizer=keras.optimizers.Adam(amsgrad=True)

classifier.compile(optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.5750 - accuracy: 0.7956
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4400 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4325 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4293 - accuracy: 0.7960
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4278 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4258 - accuracy: 0.7960
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4232 - accuracy: 0.7960
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4211 - accuracy: 0.7960
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8051
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4184 - accura

In [33]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 806us/step


array([[1542,   53],
       [ 263,  142]], dtype=int64)

In [34]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  84.2 %
